apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exposr.fullname" . }}
  labels:
    {{- include "exposr.labels" . | nindent 4 }}
data:
  EXPOSR_LOG_LEVEL: "{{ index .Values.exposr "log-level" }}"
  EXPOSR_ADMIN_ENABLE: "true"
  EXPOSR_ADMIN_PORT: "8081"
  EXPOSR_PORT: "8080"
{{- if index .Values.exposr "api-url" }}
  EXPOSR_API_URL: "{{ index .Values.exposr "api-url" }}"
{{- end }}
  EXPOSR_INGRESS_0: "http"
  EXPOSR_HTTP_INGRESS_DOMAIN: "{{ index .Values.exposr "http-ingress-domain" }}"
  EXPOSR_ALLOW_REGISTRATION: "{{ index .Values.exposr "allow-registration" }}"
{{- if index .Values.exposr "redis-url" }}
  EXPOSR_REDIS_URL: "{{ index .Values.exposr "redis-url" }}"
{{- end }}
