apiVersion: v1
kind: Service
metadata:
  name: {{ include "exposr.fullname" . }}
  labels:
    {{- include "exposr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "exposr.selectorLabels" . | nindent 4 }}
