apiVersion: v1
kind: Service
metadata:
  name: {{ include "exposr.fullname" . }}
  labels:
    {{- include "exposr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.adminApiPort }}
      targetPort: admin-api
      protocol: TCP
      name: admin-api
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
{{- if eq .Values.exposr.ingress.sni.enabled true }}
    - port: {{ .Values.exposr.ingress.sni.servicePort }}
      targetPort: ingress-sni
      protocol: TCP
      name: ingress-sni
{{- end }}
{{- if eq .Values.exposr.transport.ssh.enabled true }}
    - port: {{ .Values.exposr.transport.ssh.servicePort }}
      targetPort: transport-ssh
      protocol: TCP
      name: transport-ssh
{{- end }}
  selector:
    {{- include "exposr.selectorLabels" . | nindent 4 }}
