replicaCount: 1


exposr:
  logLevel: info
  allowRegistration: false
  adminApiKey: ""
  transport:
    ws:
      enabled: true
    ssh:
      enabled: false
      port: 2200
      servicePort: 22
      host: ""
      key: ""
  ingress:
    http:
      enabled: false
      domain: ""
    sni:
      enabled: false
      port: 4430
      servicePort: 443
      cert: ""
  envs: {}

image:
  repository: docker.io/exposr/exposr-server
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  adminPort: 8081

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

ingressAdmin:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
